#!/usr/bin/env sh
# Install the user-facing `routines` CLI shim and align the live launchd entries
# with the same checkout so PATH and launchd never disagree.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source_bin="$repo_root/bin/routines"
cli_entry="$repo_root/src/cli.ts"
compiled="$repo_root/dist/routines"

if [ ! -x "$source_bin" ]; then
  chmod +x "$source_bin" 2>/dev/null || true
fi
if [ ! -x "$compiled" ]; then
  chmod +x "$compiled" 2>/dev/null || true
fi

has_source=0
has_compiled=0
[ -f "$cli_entry" ] && has_source=1
[ -x "$compiled" ] && has_compiled=1

if [ "$has_source" -eq 1 ]; then
  if [ ! -f "$source_bin" ]; then
    echo "routines shim source not found: $source_bin" >&2
    exit 1
  fi
  shim_target="$source_bin"
elif [ "$has_compiled" -eq 1 ]; then
  shim_target="$compiled"
else
  echo "routines CLI entry not found: need $cli_entry or $compiled" >&2
  exit 1
fi

if [ "${ROUTINES_INSTALL_BIN:-}" ]; then
  install_bin=$ROUTINES_INSTALL_BIN
elif [ -d "$HOME/.local/bin" ] || case ":$PATH:" in *":$HOME/.local/bin:"*) true ;; *) false ;; esac; then
  install_bin=$HOME/.local/bin
elif case ":$PATH:" in *":$HOME/bin:"*) true ;; *) false ;; esac; then
  install_bin=$HOME/bin
else
  install_bin=$HOME/.local/bin
fi

mkdir -p "$install_bin"
ln -sf "$shim_target" "$install_bin/routines"

# Zero-LLM north-star-rollup gate (optional registry gate_command target).
ns_gate="$repo_root/scripts/north-star-rollup-gate.sh"
if [ -f "$ns_gate" ]; then
  chmod +x "$ns_gate" 2>/dev/null || true
  ln -sf "$ns_gate" "$install_bin/routines-north-star-rollup-gate"
fi

# Zero-LLM cloud-sync-health-fix observe gate (avoids 45m exit-124 with no metrics).
cshf_gate="$repo_root/scripts/cloud-sync-health-fix-gate.sh"
if [ -f "$cshf_gate" ]; then
  chmod +x "$cshf_gate" 2>/dev/null || true
  ln -sf "$cshf_gate" "$install_bin/routines-cloud-sync-health-fix-gate"
fi

# Zero-LLM LastDB real-data smoke gate. The scheduled canary must never spend
# its harness wall clock compiling Fold; a separate 180-minute builder stages
# candidate binaries for this bounded probe.
lastdb_smoke_gate="$repo_root/scripts/lastdb-local-smoke-gate.sh"
if [ -f "$lastdb_smoke_gate" ]; then
  chmod +x "$lastdb_smoke_gate" 2>/dev/null || true
  ln -sf "$lastdb_smoke_gate" "$install_bin/routines-lastdb-local-smoke-gate"
fi

# Keep launchd run-daemon on the same checkout as the PATH shim. Operators used
# to pin ROUTINES_CLI at a disposable worktree while ~/.local/bin/routines still
# pointed at a stale/broken tree — status then failed on import while the daemon
# kept running.
routines_home="${ROUTINES_HOME:-$HOME/.routines}"
daemon_dir="$routines_home/daemon"
mkdir -p "$daemon_dir"
run_daemon="$daemon_dir/run-daemon.sh"
run_web="$daemon_dir/run-web.sh"
run_hygiene="$daemon_dir/run-hygiene.sh"

# Runtime resolver shared by generated launchd entrypoints.
# Compiled host-track current is an executable (not *.ts): exec it.
# Source checkouts fall back to bun $root/src/cli.ts only when that file exists.
# Never bake a generate-time worktree path as ROUTINES_CLI default.
if [ "$has_source" -eq 1 ]; then
  source_fallback=$(cat <<'EOF'
    if [ -n "$resolved" ]; then
      root="$(CDPATH= cd -- "$(dirname -- "$resolved")/.." && pwd 2>/dev/null || true)"
      if [ -n "$root" ] && [ -f "$root/src/cli.ts" ]; then
        exec "$bun_bin" "$root/src/cli.ts" "$@"
      fi
    fi
EOF
)
else
  source_fallback=""
fi

write_run_script() {
  dest="$1"
  header="$2"
  extras="$3"
  exec_args="$4"
  cat >"$dest" <<EOF
#!/usr/bin/env bash
$header
set -euo pipefail

export ROUTINES_HOME="\${ROUTINES_HOME:-$routines_home}"
export HOME="\${HOME:-$HOME}"
export USER="\${USER:-}"
export PATH="\${PATH:-/usr/bin:/bin}:\$HOME/.local/bin:\$HOME/.bun/bin:\$HOME/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin"
$extras
bun_bin="\${ROUTINES_BUN_BIN:-\$HOME/.bun/bin/bun}"
shim="\${ROUTINES_SHIM:-$install_bin/routines}"

resolve_cli() {
  python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "\$1" 2>/dev/null || true
}

exec_routines() {
  if [ -n "\${ROUTINES_CLI:-}" ]; then
    case "\$ROUTINES_CLI" in
      *.ts)
        exec "\$bun_bin" "\$ROUTINES_CLI" "\$@"
        ;;
      *)
        exec "\$ROUTINES_CLI" "\$@"
        ;;
    esac
  fi

  if [ -L "\$shim" ] || [ -f "\$shim" ]; then
    resolved="\$(resolve_cli "\$shim")"
    if [ -n "\$resolved" ] && [ -x "\$resolved" ]; then
      case "\$resolved" in
        *.ts) ;;
        *) exec "\$resolved" "\$@" ;;
      esac
    fi
$source_fallback
  fi
  echo "routines: could not resolve a live CLI from \$shim" >&2
  exit 127
}

$exec_args
EOF
  chmod +x "$dest"
}

write_run_script "$run_daemon" \
  "# routinesd launchd entrypoint — generated by scripts/install-shim.sh.
# Resolves the installed shim at runtime so compiled host-track current
# (dist/routines) is exec'd; bun source CLI is used only when that file exists." \
  '
if [ -f "$HOME/.config/secrets.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$HOME/.config/secrets.env"
  set +a
fi

# 0 = unlimited free-slot pool (default). Set ROUTINES_CONCURRENCY to a positive
# integer only if you intentionally want a hard global cap.
CONCURRENCY="${ROUTINES_CONCURRENCY:-0}"
' \
  'exec_routines daemon --concurrency "$CONCURRENCY"'

write_run_script "$run_web" \
  "# routines web dashboard launchd entrypoint — generated by scripts/install-shim.sh.
# Resolves the installed shim at runtime so compiled host-track current
# (dist/routines) is exec'd; bun source CLI is used only when that file exists." \
  '
PORT="${ROUTINES_WEB_PORT:-4778}"
HOST="${ROUTINES_WEB_HOST:-127.0.0.1}"
' \
  'exec_routines web --port "$PORT" --host "$HOST"'

write_run_script "$run_hygiene" \
  "# routines hygiene launchd entrypoint — generated by scripts/install-shim.sh.
# Resolves the installed shim at runtime so path drift from an old checkout
# does not strand the hygiene watchdog." \
  '
if [ -f "$HOME/.config/secrets.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$HOME/.config/secrets.env"
  set +a
fi
' \
  'exec_routines hygiene --json --ff-install'

# Reload launchd so a rewritten run-web.sh is picked up. kickstart does not
# reload plist contents; bootout+bootstrap does. Skip when ROUTINES_HOME is a
# test sandbox (not the live ~/.routines) so hermetic tests never touch agents.
reload_launchd_if_live() {
  if [ "${ROUTINES_SKIP_LAUNCHD_RELOAD:-}" = "1" ]; then
    return 0
  fi
  live_home="${HOME}/.routines"
  if [ "$routines_home" != "$live_home" ]; then
    return 0
  fi
  uid=$(id -u)
  agents="${HOME}/Library/LaunchAgents"
  web_label="com.edgevector.routines-web"
  web_plist="${agents}/${web_label}.plist"
  if [ -f "$web_plist" ]; then
    launchctl bootout "gui/${uid}/${web_label}" >/dev/null 2>&1 || true
    launchctl bootstrap "gui/${uid}" "$web_plist" >/dev/null 2>&1 || true
  fi
  daemon_label="com.edgevector.routinesd"
  daemon_plist="${agents}/${daemon_label}.plist"
  if [ -f "$daemon_plist" ]; then
    daemon_args=$(plutil -extract ProgramArguments json -o - "$daemon_plist" 2>/dev/null || true)
    case "$daemon_args" in
      *src/cli.ts*|*run-daemon.sh*)
        launchctl bootout "gui/${uid}/${daemon_label}" >/dev/null 2>&1 || true
        launchctl bootstrap "gui/${uid}" "$daemon_plist" >/dev/null 2>&1 || true
        ;;
    esac
  fi
}

reload_launchd_if_live

echo "Installed routines shim: $install_bin/routines -> $shim_target"
echo "Aligned daemon entry: $run_daemon (runtime resolve via $install_bin/routines)"
echo "Aligned web entry: $run_web (runtime resolve via $install_bin/routines)"
echo "Aligned hygiene entry: $run_hygiene (runtime resolve via $install_bin/routines)"
