#!/usr/bin/env sh
# Install the user-facing `routines` CLI shim and align the live launchd entries
# with the same checkout so PATH and launchd never disagree.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source_bin="$repo_root/bin/routines"
cli_entry="$repo_root/src/cli.ts"

if [ ! -x "$source_bin" ]; then
  chmod +x "$source_bin" 2>/dev/null || true
fi
if [ ! -f "$source_bin" ]; then
  echo "routines shim source not found: $source_bin" >&2
  exit 1
fi
if [ ! -f "$cli_entry" ]; then
  echo "routines CLI entry not found: $cli_entry" >&2
  exit 1
fi

if [ "${ROUTINES_INSTALL_BIN:-}" ]; then
  install_bin=$ROUTINES_INSTALL_BIN
elif [ -d "$HOME/.local/bin" ] || case ":$PATH:" in *":$HOME/.local/bin:"*) true ;; *) false ;; esac; then
  install_bin=$HOME/.local/bin
elif case ":$PATH:" in *":$HOME/bin:"*) true ;; *) false ;; esac; then
  install_bin=$HOME/bin
else
  install_bin=$HOME/.local/bin
fi

mkdir -p "$install_bin"
ln -sf "$source_bin" "$install_bin/routines"

# Keep launchd run-daemon on the same checkout as the PATH shim. Operators used
# to pin ROUTINES_CLI at a disposable worktree while ~/.local/bin/routines still
# pointed at a stale/broken tree — status then failed on import while the daemon
# kept running.
routines_home="${ROUTINES_HOME:-$HOME/.routines}"
daemon_dir="$routines_home/daemon"
mkdir -p "$daemon_dir"
run_daemon="$daemon_dir/run-daemon.sh"
run_web="$daemon_dir/run-web.sh"
cat >"$run_daemon" <<EOF
#!/usr/bin/env bash
# routinesd launchd entrypoint — generated by scripts/install-shim.sh.
# Always derives the CLI from the installed shim so PATH and daemon share one tree.
set -euo pipefail

export ROUTINES_HOME="\${ROUTINES_HOME:-$routines_home}"
export HOME="\${HOME:-$HOME}"
export USER="\${USER:-${USER:-tomtang}}"
export PATH="\${PATH:-/usr/bin:/bin}:\$HOME/.local/bin:\$HOME/.bun/bin:\$HOME/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin"

if [ -f "\$HOME/.config/secrets.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "\$HOME/.config/secrets.env"
  set +a
fi

# Prefer explicit ROUTINES_CLI; else resolve via the installed shim realpath.
if [ -z "\${ROUTINES_CLI:-}" ]; then
  shim="\${ROUTINES_SHIM:-$install_bin/routines}"
  if [ -L "\$shim" ] || [ -f "\$shim" ]; then
    # portable realpath (macOS has no readlink -f)
    resolved="\$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "\$shim" 2>/dev/null || true)"
    if [ -n "\$resolved" ]; then
      root="\$(CDPATH= cd -- "\$(dirname -- "\$resolved")/.." && pwd)"
      ROUTINES_CLI="\$root/src/cli.ts"
    fi
  fi
fi
ROUTINES_CLI="\${ROUTINES_CLI:-$cli_entry}"
BUN_BIN="\${ROUTINES_BUN_BIN:-\$HOME/.bun/bin/bun}"
# 0 = unlimited free-slot pool (default). Set ROUTINES_CONCURRENCY to a positive
# integer only if you intentionally want a hard global cap.
CONCURRENCY="\${ROUTINES_CONCURRENCY:-0}"

exec "\$BUN_BIN" "\$ROUTINES_CLI" daemon --concurrency "\$CONCURRENCY"
EOF
chmod +x "$run_daemon"

cat >"$run_web" <<EOF
#!/usr/bin/env bash
# routines web dashboard launchd entrypoint — generated by scripts/install-shim.sh.
# Always derives the CLI from the installed shim so PATH and launchd share one tree.
set -euo pipefail

export ROUTINES_HOME="\${ROUTINES_HOME:-$routines_home}"
export HOME="\${HOME:-$HOME}"
export USER="\${USER:-${USER:-tomtang}}"
export PATH="\${PATH:-/usr/bin:/bin}:\$HOME/.local/bin:\$HOME/.bun/bin:\$HOME/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin"

# Prefer explicit ROUTINES_CLI; else resolve via the installed shim realpath.
if [ -z "\${ROUTINES_CLI:-}" ]; then
  shim="\${ROUTINES_SHIM:-$install_bin/routines}"
  if [ -L "\$shim" ] || [ -f "\$shim" ]; then
    # portable realpath (macOS has no readlink -f)
    resolved="\$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "\$shim" 2>/dev/null || true)"
    if [ -n "\$resolved" ]; then
      root="\$(CDPATH= cd -- "\$(dirname -- "\$resolved")/.." && pwd)"
      ROUTINES_CLI="\$root/src/cli.ts"
    fi
  fi
fi
ROUTINES_CLI="\${ROUTINES_CLI:-$cli_entry}"
BUN_BIN="\${ROUTINES_BUN_BIN:-\$HOME/.bun/bin/bun}"
PORT="\${ROUTINES_WEB_PORT:-4778}"
HOST="\${ROUTINES_WEB_HOST:-127.0.0.1}"

exec "\$BUN_BIN" "\$ROUTINES_CLI" web --port "\$PORT" --host "\$HOST"
EOF
chmod +x "$run_web"

echo "Installed routines shim: $install_bin/routines -> $source_bin"
echo "Aligned daemon entry: $run_daemon (ROUTINES_CLI default -> $cli_entry)"
echo "Aligned web entry: $run_web (ROUTINES_CLI default -> $cli_entry)"
